import test from 'node:test';import assert from 'node:assert/strict';
import {summarizePrice,priceDay} from '../ai-channel-price-check.mjs';
const now=Date.parse('2026-09-09T04:00:00Z');const settings={quota_display_type:'CUSTOM',custom_currency_symbol:'￥',custom_currency_exchange_rate:1,quota_per_unit:500000};
const log=(quota,time=now)=>({type:2,model_name:'gpt-image-2',quota,created_at:time/1000});
test('actual quota stays exact; mixed prices retained and latest change detected',()=>{const r=summarizePrice([log(100000),log(50000,now-1000)],settings,'gpt-image-2',now,{model:'gpt-image-2',latestQuota:50000});assert.equal(r.status,'VERIFIED');assert.equal(r.latestQuota,100000);assert.equal(r.changed,true);assert.equal(r.mixedPrices,true);assert.equal(r.distribution['50000'],1);});
test('old records do not count as today; other models and non-consumption logs excluded',()=>{const r=summarizePrice([log(100000,now-86400000),{...log(0),type:1}],settings,'gpt-image-2',now);assert.equal(r.status,'NO_RECENT_USAGE');assert.equal(r.todayCount,0);assert.equal(r.sampleCount,1);assert.equal(priceDay('2026-09-08T16:00:00Z'),'2026-09-09');});
test('unknown currency conversion is never reported as yuan',()=>{assert.throws(()=>summarizePrice([], {...settings,quota_display_type:'USD'},'gpt-image-2',now),/UNSUPPORTED/);});
test('empty sample stays unverified and model changes are not price changes',()=>{assert.equal(summarizePrice([],settings,'gpt-image-2',now).status,'NO_RECENT_USAGE');assert.equal(summarizePrice([log(100000)],settings,'gpt-image-2',now,{model:'other',latestQuota:50000}).changed,false);});
test('already claimed day does not access credentials or query provider',async()=>{const {createChannelPriceChecker}=await import('../ai-channel-price-check.mjs');let calls=0;await createChannelPriceChecker({clock:()=>now,pool:{query:async()=>++calls===1?{rows:[{id:'x',account_id:'a'}]}:{rows:[]}},fetchFn:()=>{throw Error('must not fetch')}}).runDue();assert.equal(calls,2);});
